---
- name : Configura SELinux en modo Disabled
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=disabled
- name: Desactiva servio de Firewall
  service:
    name: firewalld
    enabled: no
    state: stopped

#- name: Parando servicio de Firewall
#  ansible.builtin.service:
#    name: firewalld
