---
- name: POSTINSTALL via role playbook
  hosts: all
  become: true

  pre_tasks:
    - debug:
        msg: 'Postinstall.'

  roles:
    - history
    - usuarios
#    - ssh_keys
    - repositorios_oci
    - paquetes_minimios
    - firewall_selinux
    - conf_locales
#    - configurar_ntp_prod
