---
- name: Aplicacion de las ssh ssh_keys via role playbook
  hosts: all
  become: true

  - name: First Task - Using shell module to check if virtualenv is present or not
    ansible.builtin.shell:
      cmd: df - /var/ |tail -n1 |awk '{print $4}'
    register: space_var
    ignore_errors: True
  - name: Run a shell command using output of the previous task
    ansible.builtin.shell: 
      cmd: yum clean all
    when: space_var < 1500000